spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ERP_Hardware_DB;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=2005
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
